# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "feat-add-pip" ]

jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Build by make
        run: make linux
  build-darwin:
    name: build-darwin
    runs-on: macos-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build by make
        run: make darwin
  build-windows:
    name: build-windows
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build by make
        run: make windows
  release:
    name: release
    runs-on: ubuntu-latest
    needs: [build-linux, build-darwin, build-windows]
    steps:
      - 
        run: ls -l *


