# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "feat-add-pip" ]

jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build by make
        run: make linux
  build-windows:
    name: build-windows
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3


